from typing import Any, Dict, Optional
from datetime import datetime, timezone
from app.repositories.base_repository import BaseRepository
from app.utils.object_id import doc_to_dict


class InstitutionSettingsRepository(BaseRepository):
    def __init__(self):
        super().__init__("institution_settings")

    async def get_settings(self) -> Dict[str, Any]:
        doc = await self.collection.find_one({})
        if not doc:
            # Create default settings record
            now = datetime.now(timezone.utc)
            default_data = {
                "institutionName": "Master University",
                "departmentName": "Department of Computer Science",
                "addressLine1": "Academic Campus, University Road",
                "addressLine2": "District Center - 600001",
                "academicTitle": "CLASS TIME TABLE",
                "logoUrl": None,
                "principalName": "Principal / Dean",
                "hodName": "Head of Department",
                "preparedByLabel": "Time Table Coordinator",
                "approvedByLabel": "Principal",
                "footerText": "Generated by Master Scheduler • Smart Scheduling. Zero Conflicts.",
                "createdAt": now,
                "updatedAt": now,
                "isActive": True,
            }
            res = await self.collection.insert_one(default_data)
            default_data["_id"] = res.inserted_id
            return doc_to_dict(default_data)
        return doc_to_dict(doc)

    async def update_settings(self, update_fields: Dict[str, Any]) -> Dict[str, Any]:
        existing = await self.get_settings()
        now = datetime.now(timezone.utc)
        payload = {k: v for k, v in update_fields.items() if v is not None}
        payload["updatedAt"] = now

        from app.utils.object_id import parse_object_id
        await self.collection.update_one(
            {"_id": parse_object_id(existing["id"])},
            {"$set": payload}
        )
        return await self.get_settings()


institution_settings_repo = InstitutionSettingsRepository()
