from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class InstitutionSettingsBase(BaseModel):
    institutionName: str = Field(default="Master University", description="Name of the university / institution")
    departmentName: str = Field(default="Department of Computer Science", description="Department or faculty name")
    addressLine1: str = Field(default="Academic Campus, University Road", description="Address line 1")
    addressLine2: Optional[str] = Field(default=None, description="Address line 2 / City / State / Pincode")
    academicTitle: str = Field(default="CLASS TIME TABLE", description="Header title printed on timetables")
    logoUrl: Optional[str] = Field(default=None, description="URL or data URI for the institution logo")
    principalName: Optional[str] = Field(default="Principal / Dean", description="Name or title for principal/dean signature")
    hodName: Optional[str] = Field(default="Head of Department", description="Name or title for HOD signature")
    preparedByLabel: str = Field(default="Time Table Coordinator", description="Label for prepared by signature")
    approvedByLabel: str = Field(default="Principal", description="Label for approved by signature")
    footerText: Optional[str] = Field(
        default="Generated by Master Scheduler • Smart Scheduling. Zero Conflicts.",
        description="Footer note on printed and exported timetables",
    )


class InstitutionSettingsCreate(InstitutionSettingsBase):
    pass


class InstitutionSettingsUpdate(BaseModel):
    institutionName: Optional[str] = None
    departmentName: Optional[str] = None
    addressLine1: Optional[str] = None
    addressLine2: Optional[str] = None
    academicTitle: Optional[str] = None
    logoUrl: Optional[str] = None
    principalName: Optional[str] = None
    hodName: Optional[str] = None
    preparedByLabel: Optional[str] = None
    approvedByLabel: Optional[str] = None
    footerText: Optional[str] = None


class InstitutionSettingsResponse(InstitutionSettingsBase):
    id: str
    updatedAt: Optional[datetime] = None
    updatedBy: Optional[str] = None
